// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZy0NHlypY_Co38EQ3TCSVC3F3Uvbd74',
    appId: '1:582120541583:web:2cbf891b995c7006c08ffa',
    messagingSenderId: '582120541583',
    projectId: 'flutter-app-611c4',
    authDomain: 'flutter-app-611c4.firebaseapp.com',
    storageBucket: 'flutter-app-611c4.firebasestorage.app',
    measurementId: 'G-7QN81KJJBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmaOnCR9PQQ4ImpDy1yBsckI10JQTNE44',
    appId: '1:582120541583:android:262c6defbad86181c08ffa',
    messagingSenderId: '582120541583',
    projectId: 'flutter-app-611c4',
    storageBucket: 'flutter-app-611c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnPdiwQGXeqUkm_HE2weCgL_IcrL_kvQ',
    appId: '1:582120541583:ios:6b346c6ec65f4391c08ffa',
    messagingSenderId: '582120541583',
    projectId: 'flutter-app-611c4',
    storageBucket: 'flutter-app-611c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFnPdiwQGXeqUkm_HE2weCgL_IcrL_kvQ',
    appId: '1:582120541583:ios:6b346c6ec65f4391c08ffa',
    messagingSenderId: '582120541583',
    projectId: 'flutter-app-611c4',
    storageBucket: 'flutter-app-611c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrZy0NHlypY_Co38EQ3TCSVC3F3Uvbd74',
    appId: '1:582120541583:web:673cf344e327ae88c08ffa',
    messagingSenderId: '582120541583',
    projectId: 'flutter-app-611c4',
    authDomain: 'flutter-app-611c4.firebaseapp.com',
    storageBucket: 'flutter-app-611c4.firebasestorage.app',
    measurementId: 'G-142QRVD2MP',
  );
}
